hash-format = "sha256"

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "db026135a8a23b2b660ebbfa8a85d06b26249305b2612bc2fab930e252100890"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "5525cfe500a324b4415516770d584eab9b0f6ca64286c55547b5403e76f63b3b"
metafile = true

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "404e54caedda19b747d38c643200477ed9a13b9b522e0fed689244d1bf778200"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "571293a6ddb6b5ea7b9c1f5454d0cfc584a5aa50397942bea4906d3b54e02e02"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4ca8b963965342aafdfe251e5306259eb9cf459d43e46d9695974dcff01465aa"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "e587e79637fbc8dc23f29d51e2c4a685a3bcfbdb28b24452620dedbab8e7368c"
metafile = true

[[files]]
file = "mods/bbrb.pw.toml"
hash = "a2133cba48ed81c5c37edbf37bbdc878bfd9eaf1ac679a7311532b7dd04c273d"
metafile = true

[[files]]
file = "mods/better-fps-render-distance.pw.toml"
hash = "422e9de11c4996c14a0a907cfe627428c7c52e9ee55c8da0193236038da02680"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "105896bd81709c51629f3950e53c41765bc413f6d44edef7e776db8eb8e544b2"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "03ed171e9783a6a2f7d7543951476d23829e7e9c226318dbb006a4b4c2fb7a29"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "5488558b52cdbacdc991c1f76b658c49a3c40f53ddf49a22df988d516bcdcfc7"
metafile = true

[[files]]
file = "mods/chunky-offline.pw.toml"
hash = "18cead0149f4d8d9533e03372d5ed4d1fdca927790f48878876b01c3d8d5fb9e"
metafile = true

[[files]]
file = "mods/chunky-pregenerator-forge.pw.toml"
hash = "7be63eaec6a70605f2f21cc30f0889fb27978c2e2fe62ee4584210502289e77d"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
hash = "1f41272b5cdabe73dc343bdb89eb9993c82df611a18182dcbc7107a46b7458bb"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "22286fa216349c0767808903a0a38662857d2adee54950a18cbf26c167a06029"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "81105a1a363873f3675a861d228abcf0f2a8356f1a17850c06f6d6c47e454634"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "f2b5f72cda84b07adc4db105d81c9c2bb3cebb119a85efe0a9cfdd62d0133101"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "92d8711662b4e3fd42a57254571aca9f0b33a10bb7492a8fba59b22e78f688e6"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f92e7a06645e41ea1934dc420eb2772edb1708c0d71cb427baef8cf753acb934"
metafile = true

[[files]]
file = "mods/dimthreads.pw.toml"
hash = "b67667c6ec8e3a755c0b05f81930e4f77b5a1269aed6afd4d2ae889ca05ae020"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "701f50586a41684c3868b80708584f42dde8ff5bef0585abb418e5de4caa0468"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "f619c1ed2e189f9d482d081411fccee4bd26c05cce52a5db914f1989303f080c"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "04cba5d12b1262ba3a1d89caae20c5e44a9010f050c549ff91f2661fb796dc7b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4c8454a265574253ae608448e14a1acf138b364cced8245c72e9c4b68fb52207"
metafile = true

[[files]]
file = "mods/essential-mod.pw.toml"
hash = "8798002c827cbcbbad849f4160026e32c7ea528457ba55a10601c4eee6c7d2bf"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "5961d4df1656f866ef9f003093d822e7396db716064c1d44bb30e8936de6ce88"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/fix-gpu-memory-leak.pw.toml"
hash = "e70c20bf24819da470d25d8cfe9cd07d2fc4ace4de942e7bcd38f7a674a24b6c"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "c595b64a055d987de9d4ce6156c88eec58cf1b1ade849ff11731307f64a60941"
metafile = true

[[files]]
file = "mods/get-it-together-drops.pw.toml"
hash = "2b527d9cc1b1b919deae4a829f39c71b447a5012332809ade812971eae06bf7d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6c275f621e7c3895ed34ee0e5bf847916a4285ac0f6452982ad6dccd5dd59851"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "6e40a993b6ad3ebf94b6771b9a31d17414d2949ece938c7fa69f2bb93f75baec"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "6b3f722168fa57e23fca5441d9b74a11194d9252625d6bf0898c4d212f99380a"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "2adc7a51ce009ed3e7c1e0d22fd71ad2c152796d8e0ab6cda1447bf89d6404bb"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "f3c65260852c67a57fe761cde9fa9340525857942057379d4c9e492591507c65"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7fbe3225c134e823a07f3aecedace39fe866f327671ecca928f134399b94008d"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "62bd491a40d4978487900efadc26a2c10da6ccad88683c9b77379f7dcea8d938"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "885976c7e80d47800b5fe6dc614097772cc88f908160abd50fcdebcda7e1270c"
metafile = true

[[files]]
file = "mods/leaky.pw.toml"
hash = "6ac68f7b97f37aa2fa4083f61682c7ea95a3bacb52854c6c4454dfbb0967658a"
metafile = true

[[files]]
file = "mods/let-me-despawn.pw.toml"
hash = "dd4dd28e505ef8a6dae0569c92b03732302094e952068db010924fe945a27170"
metafile = true

[[files]]
file = "mods/limited-chunkloading.pw.toml"
hash = "fb88337b7840e3c06138a63aca65fbaedf6bb8aaca6fd91bc8154d3c27db7846"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3ac8c76f4cb2f1200d60fa2e74108d9cb9355346ddb8a4a735134dfac7b77136"
metafile = true

[[files]]
file = "mods/magnesium-extras.pw.toml"
hash = "af6b190e42b601eb0e2ca6fd58209f0242ab8c403996f1814956a6699dcd4f86"
metafile = true

[[files]]
file = "mods/model-gap-fix.pw.toml"
hash = "0f697b680492ec68f4db792705f84f27fa54afacba3c92a578e2c1b821bc894f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97521b85e74dfbc642b9102a46be0cdda07b9cfe36aba027a3878054f93ccfcb"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "2bdee19bd39b4bd411d7c858a7978ca9d2bdda41c1cf15920ea6be0014663f79"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "5552f19bf64b1151452efdd0848611ce417e1073e48639910f8a7fdb4a9ac803"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8b725f1822c0feab9e51bef600f2ee6f4c26efbb55aa3ee9073a027f1f134202"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "eab2f56ff9135b3b7253ea5a73deae2f887e2876f5f0432936044a6e926937b4"
metafile = true

[[files]]
file = "mods/recipe-essentials-forge-fabric.pw.toml"
hash = "fba0893c1da8c6e93beb9dac0e03228ebc108e3016a44d43c6e4d1faea2a16f2"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6a48780ffd4bc3b941f81232c84034aba5ff7645ea635c604de6df71e6596bb3"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
hash = "8a0271e7d5c8f4badd2886fd9a8ca75c5a33868ac90828cf3b5dbe932025a0fa"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
hash = "ff6934dbf3203c63dbdab3b2b3a89e82c047ad22db63d8511d737a489aac743c"
metafile = true

[[files]]
file = "mods/sodium-leaf-culling.pw.toml"
hash = "3bb7ffd04e7046fb97971271036de62b95188fbfcd56bc5cfe8907eace655aec"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "05953528b550760efecc9834796d90177e09bd0d231ce814b43578e386468a73"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "6d9eaf43c14c66465e87bf03cc5cb5ecef57b3f2e8063c52f6332d33689d30be"
metafile = true

[[files]]
file = "mods/structure-essentials-forge-fabric.pw.toml"
hash = "506c793ef226a2a774b7f7ec830745926eea7cbcf660cf0b7440823fffdc1bf2"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
hash = "185d803b0f2b5619a8f02f23544777752271b803a8d92218d80e525b41fe903a"
metafile = true
